version: "3.3"

services:
  porkbun-ddns:
    image: ghcr.io/jadolg/porkbun-ddns
    container_name: porkbun-ddns
    restart: unless-stopped
    user: "1"
    volumes:
      - ./config.yaml:/config.yaml:ro
    networks:
      - shared

networks:
  shared:
    name: shared
    external: true
