default_redirection_url: https://home.dobon.dev
theme: dark

authentication_backend:
  ldap:
    implementation: custom
    url: ldap://lldap:3890
    base_dn: dc=dobon,dc=dev
    username_attribute: uid
    additional_users_dn: ou=people
    users_filter: "(&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))"
    additional_groups_dn: ou=groups
    groups_filter: "(member={dn})"
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: displayName
    user: uid=authelia,ou=people,dc=dobon,dc=dev

storage:
  postgres:
    host: storage-postgres
    port: 5432
    database: storage
    username: authelia

session:
  name: authelia_session
  domain: dobon.dev
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M

  redis:
    host: session-redis
    port: 6379

notifier:
  smtp:
    host: smtp.gmail.com
    port: 25
    timeout: 5s
    username: the.kutu.dev@gmail.com
    sender: "Authelia <the.kutu.dev@gmail.com>"
    identifier: localhost
    subject: "Geofront: {title}"

access_control:
  default_policy: deny
  rules:
    - domain: uptime.dobon.dev
      resources:
        - "/assets"
        - "/api"
        - "/upload"
      policy: bypass
    - domain:
        - traefik.v.dobon.dev
        - pihole.v.dobon.dev
        - lldap.v.dobon.dev
        - uptime.v.dobon.dev
        - prometheus.v.dobon.dev
        - syncthing.v.dobon.dev
        - baikal.v.dobon.dev
        - navidrome.v.dobon.dev
      policy: two_factor
      subject:
        - ["group:vpn"]

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

password_policy:
  standard:
    enabled: true
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: true

identity_providers:
  oidc:
    clients:
      - id: grafana
        description: Grafana
        secret: $pbkdf2-sha512$310000$zUiQTPTf9iKjixF/CZ3b5g$nkIyyUlH9G23G35LHuSdB.Fc/J9Wx2muvhdSC/JNF8dTaDPHuIHw7PSxTBbOkTlLoHIQkLwZEbMk/eV84OOe7Q
        public: false
        authorization_policy: two_factor
        redirect_uris:
          - https://grafana.v.dobon.dev/login/generic_oauth
        scopes:
          - openid
          - profile
          - groups
          - email
        userinfo_signing_algorithm: none
      - id: vikunja
        description: Vikunja
        secret: $pbkdf2-sha512$310000$EYTI9AoF38adQqdbWAbjww$tqqXeBRF3nZRzcKAUv/1KVcYCkMothPz6u/MUHSW.JumrpRkXdoq2u0y00J1hvkwYf1MZZNpEBHnJRXeKmn2eA
        redirect_uris:
          - https://vikunja.v.dobon.dev/auth/openid/authelia
        scopes:
          - openid
          - email
          - profile
