version: "3"

services:
  traefik:
    image: traefik
    container_name: traefik
    restart: unless-stopped
    userns_mode: host
    ports:
      - 80:80
      - 443:443
    expose:
      - 8080
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml:ro
      - ./secrets:/secrets:ro
      - /srv/sync/traefik/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      shared:
        ipv4_address: 10.8.1.3
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host("traefik.v.dobon.dev")
      - traefik.http.routers.traefik.service=api@internal

      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=le
      - traefik.http.routers.traefik.tls.domains[0].main=v.dobon.dev
      - traefik.http.routers.traefik.tls.domains[0].sans=*.v.dobon.dev

      - traefik.http.routers.traefik.middlewares=authelia

      - traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://authelia.dobon.dev/
      - traefik.http.middlewares.authelia.forwardauth.trustforwardheader=true
      - traefik.http.middlewares.authelia.forwardauth.authresponseheaders=Remote-User, Remote-Groups
    environment:
      - PORKBUN_API_KEY_FILE=/secrets/porkbun_api_key.txt
      - PORKBUN_SECRET_API_KEY_FILE=/secrets/porkbun_secret_api_key.txt

networks:
  shared:
    name: shared
    external: true
