[entryPoints]
  [entryPoints.web]
    address = ":80"

    [entryPoints.web.http]
        [entryPoints.web.http.redirections]
        [entryPoints.web.http.redirections.entryPoint]
            to = "websecure"
            scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.le.acme]
  email = "the.kutu.dev@gmail.com"
  storage = "acme.json"
  [certificatesResolvers.le.acme.dnsChallenge]
    provider = "porkbun"
    delayBeforeCheck = 0

[providers.docker]
  exposedByDefault = false

[api]
  dashboard = true
  insecure = true
