version: "3"

services:
  homer:
    image: b4bz/homer
    restart: unless-stopped
    user: "1"
    expose:
      - 8080
    volumes:
      - ./assets/:/www/assets:ro
    networks:
      - shared
    labels:
      - traefik.enable=true
      - traefik.http.routers.homer.rule=Host("home.dobon.dev")

      - traefik.http.routers.homer.tls=true
      - traefik.http.routers.homer.tls.certresolver=le
      - traefik.http.routers.homer.tls.domains[0].main=dobon.dev
      - traefik.http.routers.homer.tls.domains[0].sans=*.dobon.dev

networks:
  shared:
    name: shared
    external: true
