version: "3.5"

services:
  velocity-shared:
    image: itzg/bungeecord
    container_name: velocity
    restart: unless-stopped
    user: "0"
    ports:
      - 25565:25577
    volumes:
      - /srv/sync/rei/velocity:/server
    networks:
      - shared
    environment:
      - TYPE=VELOCITY
    healthcheck:
      disable: true

  luckperms-db:
    image: postgres
    restart: unless-stopped
    user: "0"
    expose:
      - 5432
    volumes:
      - /srv/sync/rei/luckperms:/var/lib/postgresql
    networks:
      - shared
    environment:
      - POSTGRES_USER=${LUCKPERMS_POSTGRES_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/luckperms_postgres_password
      - POSTGRES_DB=${LUCKPERMS_POSTGRES_DB}
    secrets:
      - luckperms_postgres_password

  borealis:
    image: itzg/minecraft-server
    restart: unless-stopped
    userns_mode: host
    expose:
      - 25565
    volumes:
      - /srv/sync/rei/servers/borealis:/data
    networks:
      - shared
    environment:
      - TYPE=FABRIC
      - VERSION=1.20.2
      - EULA=TRUE
      - RCON_PASSWORD=${RCON_PASSWORD}

  #  paper:
  #    image: itzg/minecraft-server
  #    restart: unless-stopped
  #    environment:
  #      TYPE: "PAPER"
  #      VERSION: "1.20.2"
  #      EULA: "TRUE"
  #    volumes:
  #      - ./paper:/data #! Mover a /srv/sync
  #    expose:
  #      - 25565

secrets:
  luckperms_postgres_password:
    file: ./secrets/luckperms_postgres_password.txt

networks:
  shared:
    name: shared
    external: true
