version: "3"

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    restart: unless-stopped
    userns_mode: host
    expose:
      - 3001
    volumes:
      - /srv/sync/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime-kuma.rule=Host("uptime.v.dobon.dev")
      - traefik.http.routers.uptime-kuma.tls=true

      - traefik.http.routers.uptime-kuma.tls=true
      - traefik.http.routers.uptime-kuma.tls.certresolver=le
      - traefik.http.routers.uptime-kuma.tls.domains[0].main=v.dobon.dev
      - traefik.http.routers.uptime-kuma.tls.domains[0].sans=*.v.dobon.dev

      - traefik.http.routers.uptime-kuma-status-page.rule=Host("status.dobon.dev")

      - traefik.http.routers.uptime-kuma-status-page.tls=true
      - traefik.http.routers.uptime-kuma-status-page.tls.certresolver=le
      - traefik.http.routers.uptime-kuma-status-page.tls.domains[0].main=dobon.dev
      - traefik.http.routers.uptime-kuma-status-page.tls.domains[0].sans=*.dobon.dev

networks:
  proxy:
    name: proxy
    external: true
