version: "3.8"

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    restart: unless-stopped
    user: "0"
    ports:
      - 51820:51820/udp
    expose:
      - 51821
    volumes:
      - /srv/sync/wg-easy:/etc/wireguard
    networks:
      shared:
        ipv4_address: 10.8.1.2
    labels:
      - traefik.enable=true
      - traefik.http.services.wg-easy.loadbalancer.server.port=51821

      - traefik.http.routers.wg-easy.rule=Host("wireguard.v.dobon.dev")

      - traefik.http.routers.wg-easy.tls=true
      - traefik.http.routers.wg-easy.tls.certresolver=le
      - traefik.http.routers.wg-easy.tls.domains[0].main=v.dobon.dev
      - traefik.http.routers.wg-easy.tls.domains[0].sans=*.v.dobon.dev

      - traefik.http.routers.wg-easy.middlewares=authelia
    environment:
      - LANG=en
      - WG_HOST=null.dobon.dev
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  shared:
    name: shared
    external: true
